"""postgresql source of truth us3

Revision ID: 07c7492119e4
Revises: d305f4d1ff77
Create Date: 2026-06-19 14:05:10.235099
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '07c7492119e4'
down_revision = 'd305f4d1ff77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ticker_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_notifications_ticker_id_tickers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('portfolios',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolios_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios'))
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('setting_key', sa.String(), nullable=False),
    sa.Column('setting_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings')),
    sa.UniqueConstraint('user_id', 'setting_key', 'scope', name=op.f('uq_user_settings_user_id'), postgresql_nulls_not_distinct=True)
    )
    op.create_table('portfolio_items',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('quantity_note', sa.String(), nullable=True),
    sa.Column('cost_basis_note', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_items_portfolio_id_portfolios')),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_portfolio_items_ticker_id_tickers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_items'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_items')
    op.drop_table('user_settings')
    op.drop_table('portfolios')
    op.drop_table('notifications')
    # ### end Alembic commands ###
