"""postgresql source of truth us1

Revision ID: 40be5b7bbb1d
Revises: 
Create Date: 2026-06-18 19:54:27.343891
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '40be5b7bbb1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickers',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickers')),
    sa.UniqueConstraint('symbol', 'market', name=op.f('uq_tickers_symbol'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('analysis_requests',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('horizon', sa.String(), nullable=True),
    sa.Column('risk_profile', sa.String(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('degraded_reason', sa.Text(), nullable=True),
    sa.Column('warning_summary', sa.Text(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_analysis_requests_ticker_id_tickers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analysis_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_requests'))
    )
    op.create_table('source_documents',
    sa.Column('ticker_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_content_ref', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('revision_group_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_document_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_document_id'], ['source_documents.id'], name=op.f('fk_source_documents_supersedes_document_id_source_documents')),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_source_documents_ticker_id_tickers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_documents'))
    )
    op.create_table('analysis_results',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=True),
    sa.Column('result_type', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_data_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['analysis_requests.id'], name=op.f('fk_analysis_results_request_id_analysis_requests')),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_analysis_results_ticker_id_tickers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_results'))
    )
    op.create_table('document_chunks',
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_hash', sa.String(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_document_chunks_source_document_id_source_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('source_document_id', 'chunk_index', name=op.f('uq_document_chunks_source_document_id'))
    )
    op.create_table('reports',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('safety_status', sa.String(), nullable=False),
    sa.Column('evaluation_score', sa.Numeric(), nullable=True),
    sa.Column('disclaimer_present', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['report_versions.id'], name='fk_reports_current_version', use_alter=True),
    sa.ForeignKeyConstraint(['request_id'], ['analysis_requests.id'], name=op.f('fk_reports_request_id_analysis_requests')),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_reports_ticker_id_tickers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_table('structured_log_events',
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('ticker_id', sa.UUID(), nullable=True),
    sa.Column('node_name', sa.String(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('evaluation_score', sa.Numeric(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['analysis_requests.id'], name=op.f('fk_structured_log_events_request_id_analysis_requests')),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_structured_log_events_ticker_id_tickers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_structured_log_events'))
    )
    op.create_table('workflow_node_runs',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('node_name', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('evaluation_score', sa.Numeric(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['analysis_requests.id'], name=op.f('fk_workflow_node_runs_request_id_analysis_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_node_runs')),
    sa.UniqueConstraint('request_id', 'node_name', 'attempt_number', name=op.f('uq_workflow_node_runs_request_id'))
    )
    op.create_table('evidence_items',
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('ticker_id', sa.UUID(), nullable=True),
    sa.Column('analysis_result_id', sa.UUID(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], name=op.f('fk_evidence_items_analysis_result_id_analysis_results')),
    sa.ForeignKeyConstraint(['request_id'], ['analysis_requests.id'], name=op.f('fk_evidence_items_request_id_analysis_requests')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_evidence_items_source_document_id_source_documents')),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_evidence_items_ticker_id_tickers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_items')),
    sa.UniqueConstraint('evidence_id', name=op.f('uq_evidence_items_evidence_id'))
    )
    op.create_table('report_versions',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('report_markdown', sa.Text(), nullable=False),
    sa.Column('created_by_node', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_report_versions_report_id_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_versions')),
    sa.UniqueConstraint('report_id', 'version_number', name=op.f('uq_report_versions_report_id'))
    )
    op.create_table('report_evidence_citations',
    sa.Column('report_version_id', sa.UUID(), nullable=False),
    sa.Column('evidence_item_id', sa.UUID(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], name=op.f('fk_report_evidence_citations_evidence_item_id_evidence_items')),
    sa.ForeignKeyConstraint(['report_version_id'], ['report_versions.id'], name=op.f('fk_report_evidence_citations_report_version_id_report_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_evidence_citations')),
    sa.UniqueConstraint('report_version_id', 'evidence_item_id', 'section_name', 'claim_text', name=op.f('uq_report_evidence_citations_report_version_id'))
    )
    op.create_foreign_key('fk_reports_current_version', 'reports', 'report_versions', ['current_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_reports_current_version', 'reports', type_='foreignkey')
    op.drop_table('report_evidence_citations')
    op.drop_table('report_versions')
    op.drop_table('evidence_items')
    op.drop_table('workflow_node_runs')
    op.drop_table('structured_log_events')
    op.drop_table('reports')
    op.drop_table('document_chunks')
    op.drop_table('analysis_results')
    op.drop_table('source_documents')
    op.drop_table('analysis_requests')
    op.drop_table('users')
    op.drop_table('tickers')
    # ### end Alembic commands ###
