"""add query indexes

Revision ID: 56464a69bd55
Revises: 07c7492119e4
Create Date: 2026-06-19 17:41:49.816954
"""
from alembic import op
import sqlalchemy as sa


revision = '56464a69bd55'
down_revision = '07c7492119e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_evidence_items_request_id'), 'evidence_items', ['request_id'], unique=False)
    op.create_index('ix_index_projection_status_source', 'index_projection_status', ['source_table', 'source_id'], unique=False)
    op.create_index(op.f('ix_index_projection_status_status'), 'index_projection_status', ['status'], unique=False)
    op.create_index('ix_notifications_user_id_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_portfolio_items_portfolio_id'), 'portfolio_items', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolio_items_portfolio_id'), table_name='portfolio_items')
    op.drop_index('ix_notifications_user_id_created_at', table_name='notifications')
    op.drop_index(op.f('ix_index_projection_status_status'), table_name='index_projection_status')
    op.drop_index('ix_index_projection_status_source', table_name='index_projection_status')
    op.drop_index(op.f('ix_evidence_items_request_id'), table_name='evidence_items')
    # ### end Alembic commands ###
