"""provider contract records

Revision ID: 8f1a2b3c4d5e
Revises: 56464a69bd55
Create Date: 2026-06-22 14:57:16.753753
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '8f1a2b3c4d5e'
down_revision = '56464a69bd55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_technical_analysis_results',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('source_market_data_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('indicator_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trend_state', sa.String(), nullable=True),
    sa.Column('momentum_state', sa.String(), nullable=True),
    sa.Column('volatility_state', sa.String(), nullable=True),
    sa.Column('normalization_status', sa.String(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['analysis_requests.id'], name=op.f('fk_provider_technical_analysis_results_request_id_analysis_requests')),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_provider_technical_analysis_results_ticker_id_tickers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_technical_analysis_results'))
    )
    op.create_table('provider_wave_analysis_results',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('source_market_data_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidate_summary', sa.Text(), nullable=True),
    sa.Column('rule_statuses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confirmation_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('invalidation_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uncertainty_notes', sa.Text(), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['analysis_requests.id'], name=op.f('fk_provider_wave_analysis_results_request_id_analysis_requests')),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_provider_wave_analysis_results_ticker_id_tickers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_wave_analysis_results'))
    )
    op.create_table('raw_provider_responses',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('provider_kind', sa.String(), nullable=False),
    sa.Column('provider_request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_ref', sa.String(), nullable=True),
    sa.Column('payload_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_hash', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['analysis_requests.id'], name=op.f('fk_raw_provider_responses_request_id_analysis_requests')),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_raw_provider_responses_ticker_id_tickers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_provider_responses'))
    )
    op.create_table('provider_company_profiles',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('raw_response_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('normalization_status', sa.String(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_response_id'], ['raw_provider_responses.id'], name=op.f('fk_provider_company_profiles_raw_response_id_raw_provider_responses')),
    sa.ForeignKeyConstraint(['request_id'], ['analysis_requests.id'], name=op.f('fk_provider_company_profiles_request_id_analysis_requests')),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_provider_company_profiles_ticker_id_tickers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_company_profiles'))
    )
    op.create_table('provider_financial_metrics',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('raw_response_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('normalization_status', sa.String(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_response_id'], ['raw_provider_responses.id'], name=op.f('fk_provider_financial_metrics_raw_response_id_raw_provider_responses')),
    sa.ForeignKeyConstraint(['request_id'], ['analysis_requests.id'], name=op.f('fk_provider_financial_metrics_request_id_analysis_requests')),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_provider_financial_metrics_ticker_id_tickers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_financial_metrics'))
    )
    op.create_table('provider_news_events',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('raw_response_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('sentiment_label', sa.String(), nullable=True),
    sa.Column('risk_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalization_status', sa.String(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_response_id'], ['raw_provider_responses.id'], name=op.f('fk_provider_news_events_raw_response_id_raw_provider_responses')),
    sa.ForeignKeyConstraint(['request_id'], ['analysis_requests.id'], name=op.f('fk_provider_news_events_request_id_analysis_requests')),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_provider_news_events_ticker_id_tickers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_news_events'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_news_events')
    op.drop_table('provider_financial_metrics')
    op.drop_table('provider_company_profiles')
    op.drop_table('raw_provider_responses')
    op.drop_table('provider_wave_analysis_results')
    op.drop_table('provider_technical_analysis_results')
    # ### end Alembic commands ###
