"""postgresql source of truth us2

Revision ID: d305f4d1ff77
Revises: 40be5b7bbb1d
Create Date: 2026-06-19 12:19:27.894935
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd305f4d1ff77'
down_revision = '40be5b7bbb1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_projection_status',
    sa.Column('source_table', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_system', sa.String(), nullable=False),
    sa.Column('projection_type', sa.String(), nullable=False),
    sa.Column('projection_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_index_projection_status')),
    sa.UniqueConstraint('target_system', 'projection_type', 'idempotency_key', name=op.f('uq_index_projection_status_target_system'))
    )
    op.create_table('keyword_terms',
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('normalized_term', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_terms')),
    sa.UniqueConstraint('normalized_term', 'language', name=op.f('uq_keyword_terms_normalized_term'), postgresql_nulls_not_distinct=True)
    )
    op.create_table('wave_scenarios',
    sa.Column('ticker_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence_label', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_wave_scenarios_ticker_id_tickers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wave_scenarios'))
    )
    op.create_table('evidence_paths',
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('ticker_id', sa.UUID(), nullable=True),
    sa.Column('path_type', sa.String(), nullable=False),
    sa.Column('path_summary', sa.Text(), nullable=False),
    sa.Column('source_node_ref', sa.String(), nullable=False),
    sa.Column('target_node_ref', sa.String(), nullable=False),
    sa.Column('confidence_label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['analysis_requests.id'], name=op.f('fk_evidence_paths_request_id_analysis_requests')),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_evidence_paths_ticker_id_tickers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_paths'))
    )
    op.create_table('wave_invalidation_conditions',
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('condition_text', sa.Text(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('threshold_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['wave_scenarios.id'], name=op.f('fk_wave_invalidation_conditions_scenario_id_wave_scenarios')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_wave_invalidation_conditions_source_document_id_source_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wave_invalidation_conditions'))
    )
    op.create_table('wave_rules',
    sa.Column('rule_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_wave_rules_source_document_id_source_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wave_rules')),
    sa.UniqueConstraint('rule_code', name=op.f('uq_wave_rules_rule_code'))
    )
    op.create_table('evidence_path_steps',
    sa.Column('evidence_path_id', sa.UUID(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('node_table', sa.String(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_path_id'], ['evidence_paths.id'], name=op.f('fk_evidence_path_steps_evidence_path_id_evidence_paths')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_path_steps')),
    sa.UniqueConstraint('evidence_path_id', 'step_index', name=op.f('uq_evidence_path_steps_evidence_path_id'))
    )
    op.create_table('wave_scenario_rules',
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['wave_rules.id'], name=op.f('fk_wave_scenario_rules_rule_id_wave_rules')),
    sa.ForeignKeyConstraint(['scenario_id'], ['wave_scenarios.id'], name=op.f('fk_wave_scenario_rules_scenario_id_wave_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wave_scenario_rules')),
    sa.UniqueConstraint('scenario_id', 'rule_id', 'role', name=op.f('uq_wave_scenario_rules_scenario_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wave_scenario_rules')
    op.drop_table('evidence_path_steps')
    op.drop_table('wave_rules')
    op.drop_table('wave_invalidation_conditions')
    op.drop_table('evidence_paths')
    op.drop_table('wave_scenarios')
    op.drop_table('keyword_terms')
    op.drop_table('index_projection_status')
    # ### end Alembic commands ###
