"""State contracts shared by LangGraph workflow nodes."""

from datetime import date, datetime
from typing import Literal, TypedDict

from pydantic import BaseModel, Field

from src.evidence.evidence_schema import EvidenceItem
from src.graph_rag.graph_schema import GraphContext


AgentName = Literal["market", "fundamental", "news"]
QuestionType = Literal[
    "technical_analysis",
    "fundamental_analysis",
    "news_risk_analysis",
    "comprehensive_report",
    "safety_or_unclear",
]
ExecutionMode = Literal["full", "selective", "degraded"]
NextNode = Literal[
    "market_node",
    "fundamental_node",
    "news_node",
    "coordinator_node",
]


class UserInput(BaseModel):
    """Validated user request for a research workflow run."""

    ticker: str
    user_query: str | None = None


class MarketAnalysis(BaseModel):
    """Market and technical-analysis output from the Market Agent."""

    ticker: str
    summary: str = ""
    trend_summary: str = ""
    momentum_summary: str = ""
    volatility_summary: str = ""
    evidence: list[EvidenceItem] = Field(default_factory=list)
    missing_data_notes: list[str] = Field(default_factory=list)


class FundamentalAnalysis(BaseModel):
    """Company fundamentals output from the Fundamental Agent."""

    ticker: str
    summary: str = ""
    valuation_summary: str = ""
    profitability_summary: str = ""
    stability_summary: str = ""
    evidence: list[EvidenceItem] = Field(default_factory=list)
    missing_data_notes: list[str] = Field(default_factory=list)


class NewsAnalysis(BaseModel):
    """News and event-risk output from the News Agent."""

    ticker: str
    summary: str = ""
    positive_factors: list[str] = Field(default_factory=list)
    negative_factors: list[str] = Field(default_factory=list)
    event_risks: list[str] = Field(default_factory=list)
    evidence: list[EvidenceItem] = Field(default_factory=list)
    missing_data_notes: list[str] = Field(default_factory=list)


class ResearchReport(BaseModel):
    """Structured research report generated by the Coordinator Agent."""

    title: str
    ticker: str
    data_date: date
    executive_summary: str
    market_section: str
    fundamental_section: str
    news_section: str
    graph_context_section: str = ""
    scenario_analysis: str
    risk_factors: str
    limitations: str
    evidence_summary: str
    disclaimer: str


class EvaluationResult(BaseModel):
    """Evaluator Agent result for report quality and safety."""

    overall_pass: bool
    source_grounding_score: float = Field(ge=0.0, le=1.0)
    numeric_consistency_score: float = Field(ge=0.0, le=1.0)
    safety_score: float = Field(ge=0.0, le=1.0)
    risk_disclosure_score: float = Field(ge=0.0, le=1.0)
    freshness_score: float = Field(ge=0.0, le=1.0)
    issues: list[str] = Field(default_factory=list)
    revision_suggestions: list[str] = Field(default_factory=list)


class SupervisorPlan(BaseModel):
    """Rule-based execution plan for supervisor-controlled routing."""

    required_agents: list[AgentName] = Field(
        default_factory=lambda: ["market", "fundamental", "news"]
    )
    completed_agents: list[AgentName] = Field(default_factory=list)
    failed_agents: list[AgentName] = Field(default_factory=list)
    skipped_agents: list[AgentName] = Field(default_factory=list)
    next_node: NextNode
    rationale: str = ""
    allow_degraded_report: bool = True
    question_type: QuestionType | None = None
    execution_mode: ExecutionMode | None = None
    risk_focus: bool = False
    needs_graph_context: bool = False
    routing_reason: str = ""
    planned_agent_order: list[AgentName] = Field(default_factory=list)
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    used_llm: bool = False
    fallback_used: bool = False


class WorkflowError(BaseModel):
    """Recoverable or terminal workflow error."""

    node: str
    message: str
    error_type: str = "workflow_error"
    recoverable: bool = True
    created_at: datetime = Field(default_factory=datetime.utcnow)


class GraphState(TypedDict, total=False):
    """Mutable LangGraph state passed between workflow nodes."""

    run_id: str
    user_input: UserInput
    ticker: str
    status: Literal["pending", "running", "success", "degraded", "failed"]
    market_analysis: MarketAnalysis
    fundamental_analysis: FundamentalAnalysis
    news_analysis: NewsAnalysis
    evidence: list[EvidenceItem]
    draft_report: ResearchReport
    final_report: ResearchReport
    evaluation_result: EvaluationResult
    supervisor_plan: SupervisorPlan
    graph_context: GraphContext | None
    completed_agents: list[AgentName]
    failed_agents: list[AgentName]
    skipped_agents: list[AgentName]
    agent_execution_order: list[AgentName]
    next_agent: AgentName | None
    errors: list[WorkflowError]
    warnings: list[str]
    retry_counts: dict[str, int]
    rewrite_attempts: int
    started_at: datetime
    completed_at: datetime
